### ISSUE TITLE
Incorrect formatting with calc

### ISSUE THREAD

**Issue by AlexanderArvidsson** [mohammadsiyou/prettier-plugin-twin.macro#10]
Great plugin, really helps keep things consistent!

I've strumbled upon a problem after upgrading, the formatting is breaking the classes.

Example: `inset-y-0 right-0 w-[80rem] max-w-[100vw] sm:max-w-[calc(100vw - 10rem)]`

Auto-formatted to: `100vw - 10rem ] inset-y-0 right-0 w-[80rem] max-w-[100vw] sm:max-w-[calc`

It seems to strip away the parenthesis in the calc, and then formats it as if it's its own classes?
I'd expect it to not touch it at all since it's already sorted.

**Comment by mohammadsiyou** [comment]
Sorry for inconvenience we are working on fixing it.

**Comment by FFGFlash** [comment]
To add to this any css value that requires parenthesis doesn't get formatted correctly.
``w-[calc(100% + 5rem)]`` or ``p-[var(--padding)]`` either throw a prettier error, or get formatted completely wrong.

**Comment by mohammadsiyou** [comment]
@AlexanderArvidsson @FFGFlash 
New version is released and bugs are fixed.
