### ISSUE TITLE
No release for latest changes

### ISSUE THREAD

**Issue by zax-xyz** [mohammadsiyou/prettier-plugin-twin.macro#5]
There's been some changes made in #4 (merged in August), but there's been no new releases made since then, meaning the only way to get these latest changes (which are necessary with any version of `typescript-eslint` above 5.x (released October 2021 - over a year ago)) is through Git (`yarn add -D https://github.com/mohammadsiyou/prettier-plugin-twin.macro`). It would be nice if the version in NPM was updated with these changes so the plugin is usable through the regular method.

**Comment by mohammadsiyou** [comment]
@zaxutic 
Thanks for reporting!
New version released.
